from Qt import QtWidgets


DATA_ITEMS = {
    'str': {
        'default': '',
        'widget': QtWidgets.QLineEdit,
        'bg_color': [0, 0, 0],
        'bg_alpha': 255,
        'text_color': [0, 0, 0],
        'text_alpha': 255,
        'size': 10,
        'bold': False,
        'column_size': 200,
        'editable': True,
        'expand': False,
        'paint': False,
        'toolTip': ''
    },
    'float': {
        'default': 0.0,
        'min': -9999,
        'max': 9999,
        'step': 0.01,
        'widget': QtWidgets.QDoubleSpinBox,
        'bg_color': [0, 0, 0],
        'bg_alpha': 255,
        'text_color': [0, 0, 0],
        'text_alpha': 255,
        'size': 10,
        'bold': False,
        'column_size': 200,
        'editable': True,
        'expand': False,
        'paint': False,
        'toolTip': ''
    },
    'int': {
        'default': 0,
        'min': -9999,
        'max': 9999,
        'step': 1,
        'widget': QtWidgets.QSpinBox,
        'bg_color': [0, 0, 0],
        'bg_alpha': 255,
        'text_color': [0, 0, 0],
        'text_alpha': 255,
        'size': 10,
        'bold': False,
        'column_size': 200,
        'editable': True,
        'expand': False,
        'paint': False,
        'toolTip': ''
    },
    'enum': {
        'default': None,
        'enum': [],
        'widget': QtWidgets.QComboBox,
        'bg_color': [0, 0, 0],
        'bg_alpha': 255,
        'text_color': [0, 0, 0],
        'text_alpha': 255,
        'size': 10,
        'bold': False,
        'column_size': 200,
        'editable': True,
        'expand': False,
        'paint': False,
        'toolTip': ''
    },
    'bool': {
        'default': True,
        'enum': ['True', 'False'],
        'widget': QtWidgets.QComboBox,
        'bg_color': [0, 0, 0],
        'bg_alpha': 255,
        'text_color': [0, 0, 0],
        'text_alpha': 255,
        'size': 10,
        'bold': False,
        'column_size': 200,
        'editable': True,
        'expand': False,
        'paint': False,
        'toolTip': ''
    },
    'list': {
        'default': [],
        'template': 'null',
        'widget': QtWidgets.QLineEdit,
        'bg_color': [0, 0, 0],
        'bg_alpha': 255,
        'text_color': [0, 0, 0],
        'text_alpha': 255,
        'size': 10,
        'bold': False,
        'column_size': 200,
        'editable': True,
        'expand': False,
        'paint': False,
        'toolTip': ''
    },
    'dict': {
        'default': {},
        'template': 'null',
        'widget': QtWidgets.QLineEdit,
        'bg_color': [0, 0, 0],
        'bg_alpha': 255,
        'text_color': [0, 0, 0],
        'text_alpha': 255,
        'size': 10,
        'bold': False,
        'column_size': 200,
        'editable': True,
        'expand': False,
        'paint': False,
        'toolTip': ''
    }
}
